#!/bin/bash

# Ensure script stops on errors
set -e

ARGS="-- --embedded_config Collector_velociraptor-collector"

# ZIP file to extract
ZIP_FILE="velociraptor-v0.73.zip"

# Script inside the zip to make executable and run
SCRIPT_FILE="velociraptor-v0.73.1-darwin-amd64"

# Unzip the file
unzip "$ZIP_FILE"

# Make the script executable
chmod +x "$SCRIPT_FILE"
chmod +x "upload.sh"

# Run the script with sudo and pass all arguments
sudo ./"$SCRIPT_FILE" $ARGS
